FROM --platform=linux/amd64 node:20-slim AS builder
RUN npm install -g pnpm

WORKDIR /app
COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
COPY tsconfig.base.json ./
COPY lib/api-client-react ./lib/api-client-react
COPY lib/api-spec ./lib/api-spec
COPY lib/api-zod ./lib/api-zod
COPY artifacts/hayyah-crm ./artifacts/hayyah-crm

RUN pnpm install --filter @workspace/hayyah-crm...

ARG VITE_CLIENT_SECRET
ENV VITE_CLIENT_SECRET=$VITE_CLIENT_SECRET
ARG VITE_AUTH_TOKEN_URL
ENV VITE_AUTH_TOKEN_URL=$VITE_AUTH_TOKEN_URL
ARG VITE_AUTH_BASE_URL
ENV VITE_AUTH_BASE_URL=$VITE_AUTH_BASE_URL
ARG VITE_AUTH_REFRESH_URL
ENV VITE_AUTH_REFRESH_URL=$VITE_AUTH_REFRESH_URL
ARG VITE_API_BASE_URL
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV NODE_ENV=production
ENV PORT=3000
ENV NODE_ENV=production
ARG BASE_PATH=/frontend/
ENV BASE_PATH=/frontend/

RUN pnpm --filter @workspace/hayyah-crm run build

FROM nginx:alpine
COPY --from=builder /app/artifacts/hayyah-crm/dist/public /usr/share/nginx/html
COPY artifacts/hayyah-crm/nginx.conf /etc/nginx/templates/default.conf.template
